#                                                            Developed by Senkex
#                                                        (Nautic Studios @ (C) 2026)

name: AtlasAddon
version: '${project.version}'
author: 'Senkex'

api-version: '1.16'
main: com.github.nautic.AtlasAddon

depend: [AtlasLang]